/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.itqy8.ctp;

public class CThostFtdcOptionInstrMarginAdjustField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CThostFtdcOptionInstrMarginAdjustField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcOptionInstrMarginAdjustField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CThostFtdcOptionInstrMarginAdjustField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInstrumentID(String value) {
    ctpJNI.CThostFtdcOptionInstrMarginAdjustField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ctpJNI.CThostFtdcOptionInstrMarginAdjustField_InstrumentID_get(swigCPtr, this);
  }

  public void setInvestorRange(char value) {
    ctpJNI.CThostFtdcOptionInstrMarginAdjustField_InvestorRange_set(swigCPtr, this, value);
  }

  public char getInvestorRange() {
    return ctpJNI.CThostFtdcOptionInstrMarginAdjustField_InvestorRange_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ctpJNI.CThostFtdcOptionInstrMarginAdjustField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CThostFtdcOptionInstrMarginAdjustField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpJNI.CThostFtdcOptionInstrMarginAdjustField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpJNI.CThostFtdcOptionInstrMarginAdjustField_InvestorID_get(swigCPtr, this);
  }

  public void setSShortMarginRatioByMoney(double value) {
    ctpJNI.CThostFtdcOptionInstrMarginAdjustField_SShortMarginRatioByMoney_set(swigCPtr, this, value);
  }

  public double getSShortMarginRatioByMoney() {
    return ctpJNI.CThostFtdcOptionInstrMarginAdjustField_SShortMarginRatioByMoney_get(swigCPtr, this);
  }

  public void setSShortMarginRatioByVolume(double value) {
    ctpJNI.CThostFtdcOptionInstrMarginAdjustField_SShortMarginRatioByVolume_set(swigCPtr, this, value);
  }

  public double getSShortMarginRatioByVolume() {
    return ctpJNI.CThostFtdcOptionInstrMarginAdjustField_SShortMarginRatioByVolume_get(swigCPtr, this);
  }

  public void setHShortMarginRatioByMoney(double value) {
    ctpJNI.CThostFtdcOptionInstrMarginAdjustField_HShortMarginRatioByMoney_set(swigCPtr, this, value);
  }

  public double getHShortMarginRatioByMoney() {
    return ctpJNI.CThostFtdcOptionInstrMarginAdjustField_HShortMarginRatioByMoney_get(swigCPtr, this);
  }

  public void setHShortMarginRatioByVolume(double value) {
    ctpJNI.CThostFtdcOptionInstrMarginAdjustField_HShortMarginRatioByVolume_set(swigCPtr, this, value);
  }

  public double getHShortMarginRatioByVolume() {
    return ctpJNI.CThostFtdcOptionInstrMarginAdjustField_HShortMarginRatioByVolume_get(swigCPtr, this);
  }

  public void setAShortMarginRatioByMoney(double value) {
    ctpJNI.CThostFtdcOptionInstrMarginAdjustField_AShortMarginRatioByMoney_set(swigCPtr, this, value);
  }

  public double getAShortMarginRatioByMoney() {
    return ctpJNI.CThostFtdcOptionInstrMarginAdjustField_AShortMarginRatioByMoney_get(swigCPtr, this);
  }

  public void setAShortMarginRatioByVolume(double value) {
    ctpJNI.CThostFtdcOptionInstrMarginAdjustField_AShortMarginRatioByVolume_set(swigCPtr, this, value);
  }

  public double getAShortMarginRatioByVolume() {
    return ctpJNI.CThostFtdcOptionInstrMarginAdjustField_AShortMarginRatioByVolume_get(swigCPtr, this);
  }

  public void setIsRelative(int value) {
    ctpJNI.CThostFtdcOptionInstrMarginAdjustField_IsRelative_set(swigCPtr, this, value);
  }

  public int getIsRelative() {
    return ctpJNI.CThostFtdcOptionInstrMarginAdjustField_IsRelative_get(swigCPtr, this);
  }

  public CThostFtdcOptionInstrMarginAdjustField() {
    this(ctpJNI.new_CThostFtdcOptionInstrMarginAdjustField(), true);
  }

}
